version: "3"
services:
  hub:
    image: seleniarm/hub:4.16
    ports:
      - 4444:4444
      - 4442:4442
      - 4443:4443
  chrome:
    image: seleniarm/node-chromium:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1

  firefox:
    image: seleniarm/node-firefox:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=7
      - SE_VNC_NO_PASSWORD=1
  vendor-portal:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    depends_on:
      - firefox
    volumes:
      - ${PWD}/result2:/test-output
    environment:
      - SELENIUM_GRID_ENABLED=true
      - TEST_SUITE=vendor-portal.xml
      - THREAD_COUNT=3
      - HUB_HOST=hub
  flight-reservation:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    depends_on:
      - firefox
    volumes:
      - ${PWD}/result2:/test-output
    environment:
      - SELENIUM_GRID_ENABLED=true
      - TEST_SUITE=flight-reservation.xml
      - THREAD_COUNT=4
      - HUB_HOST=hub