version: "3"
services:
  hub:
    image: seleniarm/hub:4.16
  chrome:
    image: seleniarm/node-chromium:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 2
    env_file: .env