version: "3"
services:
  vendor-portal:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result:/test-output
    env_file: .envTestSuites

  flight-reservation:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result:/test-output
    env_file: .envTestSuites