version: "3"
services:
  vendor-portal:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result/vendor-portal:/home/docker-course/test-output
    environment:
      - TEST_SUITE=vendor-portal.xml
      - BROWSER
    env_file: .envTestSuites

  flight-reservation:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result/flight-reservation:/home/docker-course/test-output
    environment:
      - TEST_SUITE=flight-reservation.xml
      - BROWSER
    env_file: .envTestSuites