version: "3"
services:
  vendor-portal:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result/vendor-portal:/home/docker-course/test-output
    env_file: .envTestSuites

  flight-reservation:
    image:  omarpixelogic/docker-aws
    shm_size: '2g'
    volumes:
      - ${PWD}/result/flight-reservation:/home/docker-course/test-output
    env_file: .envTestSuites